server:
  port: 8092

spring:
  application:
    name: client-2
  profiles:
    active: prod
  config:
    import: "configserver:http://localhost:8090"
  kafka:
    bootstrap-servers: 172.26.144.70:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
